name: example
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_video_trimmer:
    path: ../

  video_player: ^2.10.0
  file_picker: ^10.2.1
  ffmpeg_kit_flutter_new: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
